version: '3'

volumes:
  planter:

services:
  app:
    build: .
    image: planter
    command: bash -c "bundle && tail -f Gemfile"
    volumes:
      - planter:/app
    tty: true
    stdin_open: true
    tmpfs:
      - /tmp
