app:
  container_name: planter_app
  build: .
  dockerfile: Dockerfile
  volumes:
    - .:/srv/app
  volumes_from:
    - bundle_cache
bundle_cache:
  container_name: planter_bundle_cache
  image: busybox
  volumes:
    - /bundle_cache
