version: '3'

volumes:
  bundle_cache:

services:
  app:
    container_name: planter_app
    build:
      context: .
    command: >
      bash -c "test/dummy/bin/rails db:create && test/dummy/bin/rails db:migrate"
    volumes:
      - .:/srv/app
      - bundle_cache:/usr/local/lib
