volumes:
  bundle:

services:
  app:
    container_name: planter_app
    build:
      context: .
      args:
        RUBY_VERSION: ${RUBY_VERSION:-3.2}
    volumes:
      - .:/srv/app
      - bundle:/bundle
